content = open('api/main.py', 'r', encoding='utf-8').read()

old = '    mission_id = _uuid.uuid4().hex[:12]\n    _gcs_guardar(mission_id, {"status": "running", "aprobado": None, "iteracion": None, "observaciones": None, "logs": []})\n\n    def _run():\n        try:\n            if USAR_PLANNER:\n                try:\n                    submisiones_raw = planner_executor.planner.decompose(request.orden)\n                    submisiones = [{"id": s["id"], "descripcion": s["descripcion"], "status": "pending"} for s in submisiones_raw]\n                except Exception:\n                    submisiones = []\n                _gcs_guardar(mission_id, {"status": "running", "aprobado": None, "iteracion": None, "observaciones": None, "logs": [], "submisiones": submisiones})\n                resultados = planner_executor.ejecutar(sistema, request.orden)\n                resultado  = resultados[-1] if resultados else None\n            else:\n                resultado = pipeline.ejecutar_mision(sistema, request.orden)\n            _gcs_guardar(mission_id, {"status": "done", "aprobado": resultado.aprobado, "iteracion": resultado.iteracion, "observaciones": resultado.observaciones, "logs": [], "submisiones": submisiones if USAR_PLANNER else []})\n        except Exception as e:\n            _gcs_guardar(mission_id, {"status": "error", "aprobado": None, "iteracion": None, "observaciones": str(e), "logs": []})\n    threading.Thread(target=_run, daemon=True).start()'

new = '    mission_id = _uuid.uuid4().hex[:12]\n    submisiones = []\n    if USAR_PLANNER:\n        try:\n            submisiones_raw = planner_executor.planner.decompose(request.orden)\n            submisiones = [{"id": s["id"], "descripcion": s["descripcion"], "status": "pending"} for s in submisiones_raw]\n        except Exception:\n            submisiones = []\n    _gcs_guardar(mission_id, {"status": "running", "aprobado": None, "iteracion": None, "observaciones": None, "logs": [], "submisiones": submisiones})\n\n    def _run():\n        try:\n            if USAR_PLANNER:\n                resultados = planner_executor.ejecutar(sistema, request.orden)\n                resultado  = resultados[-1] if resultados else None\n            else:\n                resultado = pipeline.ejecutar_mision(sistema, request.orden)\n            _gcs_guardar(mission_id, {"status": "done", "aprobado": resultado.aprobado, "iteracion": resultado.iteracion, "observaciones": resultado.observaciones, "logs": [], "submisiones": submisiones})\n        except Exception as e:\n            _gcs_guardar(mission_id, {"status": "error", "aprobado": None, "iteracion": None, "observaciones": str(e), "logs": []})\n    threading.Thread(target=_run, daemon=True).start()'

if old in content:
    open('api/main.py', 'w', encoding='utf-8').write(content.replace(old, new))
    print('OK')
else:
    print('NO MATCH')
