path = 'utils/github_publisher.py'
c = open(path, encoding='utf-8').read()

# Fix 1: cambiar _bucket.blob por _get_bucket().blob en _leer_implementation
old1 = '                blob     = self.storage._bucket.blob(gcs_path)'
new1 = '                blob     = self.storage._get_bucket().blob(gcs_path)'
if old1 in c:
    c = c.replace(old1, new1, 1)
    print('OK fix1 _leer_implementation')
else:
    print('NO ENCONTRADO fix1')

# Fix 2: mismo fix en _leer_manifest
old2 = '''            if isinstance(self.storage, GCSStorage):
                gcs_path = manifest_path.replace("\\\\", "/").lstrip("/")
                blob     = self.storage._bucket.blob(gcs_path)'''
new2 = '''            if isinstance(self.storage, GCSStorage):
                gcs_path = manifest_path.replace("\\\\", "/").lstrip("/")
                blob     = self.storage._get_bucket().blob(gcs_path)'''
if old2 in c:
    c = c.replace(old2, new2, 1)
    print('OK fix2 _leer_manifest')
else:
    # Intentar sin escape
    old2b = '                blob     = self.storage._bucket.blob(gcs_path)'
    count = c.count(old2b)
    if count >= 2:
        # Reemplazar segunda ocurrencia (en _leer_manifest)
        idx = c.find(old2b, c.find(old2b) + 1)
        c = c[:idx] + '                blob     = self.storage._get_bucket().blob(gcs_path)' + c[idx+len(old2b):]
        print('OK fix2 segunda ocurrencia')
    else:
        print(f'NO ENCONTRADO fix2 - ocurrencias: {count}')

# Fix 3: Agregar método _generar_readme antes de publicar_mision
readme_method = '''
    def _generar_readme(self, mission_id: str, archivos: dict, manifest: dict) -> str:
        orden = manifest.get("orden_usuario", "Sistema generado por MAIIE")[:200]
        orden = re.sub(r"[\\x00-\\x1f\\x7f]", " ", orden).strip()
        compliance = manifest.get("compliance_score", 100)
        iteracion = manifest.get("iteracion_final", 1)
        timestamp = manifest.get("timestamp", "")[:10]
        modelos = manifest.get("modelos", {})
        lista_archivos = "\\n".join(f"- `{f}`" for f in sorted(archivos.keys()))

        return f"""# {mission_id}

> Generated by **MAIIE Systems** — Multi-Agent Intelligent Implementation Engine

## Description

{orden}

## Architecture

This project was autonomously designed and implemented by MAIIE using a multi-agent pipeline:

- **ARCHITECT** ({modelos.get("architect", "gemini-2.5-flash-lite")}): System design and clean architecture
- **ENGINEER** ({modelos.get("engineer", "gemini-2.5-pro")}): Full implementation
- **AUDITOR** ({modelos.get("auditor", "gemini-2.5-pro")}): Quality certification

## Quality Metrics

| Metric | Value |
|--------|-------|
| Compliance Score | {compliance}% |
| Certified in Iteration | {iteracion} |
| Generated | {timestamp} |
| DoD Status | ✅ APPROVED |

## Files

{lista_archivos}

## Stack

- Python 3.11+ with type hints
- FastAPI / React (depending on mission type)
- Clean Architecture (Core / Infrastructure / Presentation)
- Production-ready error handling

---

*Built with [MAIIE Systems](https://maiie-systems.vercel.app) by Edisson A.G.C.*
"""

'''

old3 = '    def publicar_mision('
new3 = readme_method + '    def publicar_mision('

if old3 in c:
    c = c.replace(old3, new3, 1)
    print('OK fix3 _generar_readme agregado')
else:
    print('NO ENCONTRADO fix3')

# Fix 4: Llamar _generar_readme en publicar_mision antes de subir archivos
old4 = '        repo_url, _ = self._crear_repo(repo_nombre, descripcion)\n\n        exitosos, errores = self._subir_archivos(\n            repo_nombre=repo_nombre,\n            archivos=archivos,\n            label=mission_id,'
new4 = '        repo_url, _ = self._crear_repo(repo_nombre, descripcion)\n\n        readme_content = self._generar_readme(mission_id, archivos, manifest)\n        archivos["README.md"] = readme_content\n\n        exitosos, errores = self._subir_archivos(\n            repo_nombre=repo_nombre,\n            archivos=archivos,\n            label=mission_id,'

if old4 in c:
    c = c.replace(old4, new4, 1)
    print('OK fix4 README en publicar_mision')
else:
    print('NO ENCONTRADO fix4')

open(path, 'w', encoding='utf-8').write(c)
print('DONE')
